# CppRestSdk Azure Pipelines Configuration

jobs:
  - job: Ubuntu_1604_Apt_Debug
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: sudo apt-get install -y libboost-all-dev libwebsocketpp-dev brotli libssl1.0.0
      displayName: Apt install dependencies
    - script: mkdir build.debug
      displayName: Make build.debug
    - task: CMake@1
      inputs:
        workingDirectory: 'build.debug'
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Debug -DOPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0 -DOPENSSL_SSL_LIBRARY=/usr/lib/openssl-1.0/libssl.so -DOPENSSL_CRYPTO_LIBRARY=/usr/lib/openssl-1.0/libcrypto.so ..'
    - script: |
        cd build.debug
        make
      displayName: 'Run make'
  - job: Ubuntu_1604_Apt_Release
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: sudo apt-get install -y libboost-all-dev libwebsocketpp-dev brotli libssl1.0.0
      displayName: Apt install dependencies
    - script: mkdir build.release
      displayName: Make build.release
    - task: CMake@1
      inputs:
        workingDirectory: 'build.release'
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DOPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0 -DOPENSSL_SSL_LIBRARY=/usr/lib/openssl-1.0/libssl.so -DOPENSSL_CRYPTO_LIBRARY=/usr/lib/openssl-1.0/libcrypto.so ..'
    - script: |
        cd build.release
        make
      displayName: 'Run make'
